#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
title: "Executable Book Template" # The title of the book. Will be placed in the left navbar.
author: Shawn A. Rhoads # The author of the book
copyright: '2021' # Copyright year to be placed in the footer
exclude_patterns: []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
#######################################################################################

#######################################################################################
# Execution settings
execute:
  execute_notebooks: auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  stderr_output: remove-warn

#######################################################################################

#######################################################################################
# HTML-specific settings
html:
  favicon: ""  # A path to a favicon image
  use_edit_page_button: false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button: false  # Whether to add a link to your repository button
  use_issues_button: false  # Whether to add an "open an issue" button
  extra_navbar: ""  # Will be displayed underneath the left navbar.
  extra_footer: ""  # Will be displayed underneath the footer.
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  baseurl: https://shawnrhoads.github.io/executable-notebooks-template  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false

repository:
  url: https://shawnrhoads.github.io/executable-notebooks-template # The URL to your book's repository
  branch: main  # Which branch of the repository should be used when creating links
  path_to-book: docs/ # A path to your book's folder, relative to the repository root.

footer_text: Created by <a href="http://shawnrhoads.github.io/">Shawn A Rhoads</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.
#######################################################################################

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  colab_url: ""
  binderhub_url: ""
  thebe: false  # Add a thebe button to pages (requires the repository to run on Binder)

#######################################################################################

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions:   # A list of extra extensions to load by Sphinx.
  config:   # key-value pairs to directly over-ride the Sphinx configuration
    html_theme: insipid
    html_permalinks_icon: 'ยง'
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
